#!/bin/sh

[ -t 1 ] && exec < /dev/tty

if git status --short | grep --quiet '^MM'; then
	printf '%s\n' "ERROR: Some staged files have unstaged changes" >&2
	exit 1
fi

yarn biome check --write --staged --no-errors-on-unmatched

git update-index --again
