name: Check Version

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout Project
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Automatic Release
        uses: SerenModz21/github-action-npm-release@64196018dd8b27e3b624d8e702d992ad44853f65 # master
        id: release

      - name: Display Release ID
        if: ${{ steps.release.outputs.released == 'true' }}
        run: |
          echo Release ID: "${RELEASE_ID}"
          echo Release Name: "${RELEASE_NAME}"
          echo Release Tag: "${RELEASE_TAG}"
          echo Prerelease: "${PRERELEASE}"
          echo Draft: "${DRAFT}"
          echo URL: "${HTML_URL}"
        env:
          RELEASE_ID: ${{ steps.release.outputs.release_id }}
          RELEASE_NAME: ${{ steps.release.outputs.release_name }}
          RELEASE_TAG: ${{ steps.release.outputs.release_tag }}
          PRERELEASE: ${{ steps.release.outputs.prerelease }}
          DRAFT: ${{ steps.release.outputs.draft }}
          HTML_URL: ${{ steps.release.outputs.html_url }}

      - name: Publish Version
        if: ${{ steps.release.outputs.released == 'true' }}
        run: |
          gh workflow run publish.yml -r "${RELEASE_TAG}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ steps.release.outputs.release_tag }}
