name: PR Triage

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  title:
    name: Title Validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Project
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Run Validation
        run: echo "$PR_TITLE" | bunx commitlint
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
